# Generated by Django 6.0.2 on 2026-04-20 01:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(blank=True, editable=False, help_text='Generated ONLY after payment is confirmed. NULL for pending/expired bookings.', max_length=20, null=True, unique=True)),
                ('checkin_pin', models.CharField(blank=True, editable=False, help_text='Generated ONLY after payment is confirmed. NULL for pending/expired bookings.', max_length=4, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('special_requests', models.TextField(blank=True, help_text='Optional guest requests submitted at booking time (e.g. early check-in, ground floor).', null=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('nights', models.PositiveIntegerField()),
                ('guests_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('room_price_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('full', 'Full Payment'), ('deposit', 'Deposit (30%)')], default='full', help_text='Payment type chosen by the guest at booking time.', max_length=10)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='pending_payment', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('failed', 'Failed')], default='unpaid', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='Set when booking transitions to CONFIRMED after payment.', null=True)),
                ('payment_expires_at', models.DateTimeField(blank=True, help_text='Datetime by which payment must be completed. Set to created_at + PAYMENT_WINDOW_MINUTES at booking creation. Used by frontend countdown timer.', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('refund_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_status', models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_type', models.CharField(choices=[('reschedule', 'Reschedule'), ('extend', 'Extend Stay')], max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_refund', 'Awaiting Refund'), ('confirmed', 'Confirmed'), ('payment_failed', 'Payment Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('original_check_in', models.DateField()),
                ('original_check_out', models.DateField()),
                ('original_nights', models.PositiveIntegerField()),
                ('original_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_check_in', models.DateField()),
                ('new_check_out', models.DateField()),
                ('new_nights', models.PositiveIntegerField()),
                ('new_room_price_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_difference', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('processing_fee_deduction', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Non-refundable payment processing fee deducted from refund.', max_digits=10)),
                ('penalty_deduction', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Applicable penalty (e.g. same-day reschedule) deducted from refund.', max_digits=10)),
                ('net_refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Actual refund amount after all deductions.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'booking_modifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'booking_status_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ModificationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'modification_payments',
            },
        ),
    ]
