# Generated by Django 6.0.2 on 2026-03-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Set when booking transitions to CONFIRMED after payment.', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkin_pin',
            field=models.CharField(blank=True, editable=False, help_text='Generated ONLY after payment is confirmed. NULL for pending/expired bookings.', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reference_number',
            field=models.CharField(blank=True, editable=False, help_text='Generated ONLY after payment is confirmed. NULL for pending/expired bookings.', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='pending_payment', max_length=20),
        ),
    ]
