# Generated by Django 6.0.2 on 2026-04-20 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null for walk-in / guest bookings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingmodification',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingmodification',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingstatushistory',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modificationpayment',
            name='modification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='modification_payment', to='bookings.bookingmodification'),
        ),
        migrations.AddField(
            model_name='modificationpayment',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modification_payments', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='modificationpayment',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modification_refunds', to='payments.refund'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['reference_number'], name='bookings_referen_dbb905_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_status_51373b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_in', 'check_out'], name='bookings_check_i_759ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['email'], name='bookings_email_eeb167_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room', 'check_in', 'check_out'], name='bookings_room_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingmodification',
            index=models.Index(fields=['booking', 'status'], name='booking_mod_booking_eccd84_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingmodification',
            index=models.Index(fields=['modification_type', 'status'], name='booking_mod_modific_146247_idx'),
        ),
    ]
