# Generated by Django 6.0.2 on 2026-03-20 07:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_confirmed_at_alter_booking_checkin_pin_and_more'),
        ('payments', '0004_booking_modifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_type', models.CharField(choices=[('reschedule', 'Reschedule'), ('extend', 'Extend Stay')], max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_payment', 'Awaiting Payment'), ('awaiting_refund', 'Awaiting Refund'), ('confirmed', 'Confirmed'), ('payment_failed', 'Payment Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('original_check_in', models.DateField()),
                ('original_check_out', models.DateField()),
                ('original_nights', models.PositiveIntegerField()),
                ('original_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_check_in', models.DateField()),
                ('new_check_out', models.DateField()),
                ('new_nights', models.PositiveIntegerField()),
                ('new_room_price_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_difference', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('processing_fee_deduction', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Non-refundable payment processing fee deducted from refund.', max_digits=10)),
                ('penalty_deduction', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Applicable penalty (e.g. same-day reschedule) deducted from refund.', max_digits=10)),
                ('net_refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Actual refund amount after all deductions.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='bookings.booking')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_modifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking_modifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModificationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='modification_payment', to='bookings.bookingmodification')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modification_payments', to='payments.payment')),
                ('refund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modification_refunds', to='payments.refund')),
            ],
            options={
                'db_table': 'modification_payments',
            },
        ),
        migrations.AddIndex(
            model_name='bookingmodification',
            index=models.Index(fields=['booking', 'status'], name='booking_mod_booking_eccd84_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingmodification',
            index=models.Index(fields=['modification_type', 'status'], name='booking_mod_modific_146247_idx'),
        ),
    ]
