# Generated by Django 6.0.2 on 2026-04-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_modifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_expires_at',
            field=models.DateTimeField(blank=True, help_text='Datetime by which payment must be completed. Set to created_at + PAYMENT_WINDOW_MINUTES at booking creation. Used by frontend countdown timer.', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_type',
            field=models.CharField(choices=[('full', 'Full Payment'), ('deposit', 'Deposit (30%)')], default='full', help_text='Payment type chosen by the guest at booking time.', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, help_text='Optional guest requests submitted at booking time (e.g. early check-in, ground floor).', null=True),
        ),
    ]
