# Generated by Django 6.0.2 on 2026-04-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('bookings', 'Bookings'), ('revenue', 'Revenue'), ('occupancy', 'Occupancy'), ('guests', 'Guests'), ('staff', 'Staff Performance'), ('food', 'Food & Drinks'), ('payments', 'Payments')], max_length=20)),
                ('config_snapshot', models.JSONField(default=dict, help_text='Copy of config at execution time (immutable record).')),
                ('export_format', models.CharField(choices=[('json', 'JSON (in-app)'), ('csv', 'CSV'), ('pdf', 'PDF'), ('excel', 'Excel')], max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('result_data', models.JSONField(blank=True, help_text='Full report payload (summary + rows). Null on failure.', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_executions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('bookings', 'Bookings'), ('revenue', 'Revenue'), ('occupancy', 'Occupancy'), ('guests', 'Guests'), ('staff', 'Staff Performance'), ('food', 'Food & Drinks'), ('payments', 'Payments')], db_index=True, max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Full report parameters as a JSON object.')),
                ('is_shared', models.BooleanField(default=False, help_text='If True, all Admin and Manager users can use this template.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'report_templates',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=10)),
                ('export_format', models.CharField(choices=[('json', 'JSON (in-app)'), ('csv', 'CSV'), ('pdf', 'PDF'), ('excel', 'Excel')], default='json', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('next_run', models.DateTimeField(blank=True, help_text='Datetime of next scheduled execution. Auto-updated after each run.', null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scheduled_reports',
                'ordering': ['next_run'],
            },
        ),
    ]
