# Generated by Django 6.0.2 on 2026-04-02 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('bookings', 'Bookings'), ('revenue', 'Revenue'), ('occupancy', 'Occupancy'), ('guests', 'Guests'), ('staff', 'Staff Performance')], db_index=True, max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Full report parameters as a JSON object.')),
                ('is_shared', models.BooleanField(default=False, help_text='If True, all Admin and Manager users can use this template.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_templates',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=10)),
                ('export_format', models.CharField(choices=[('json', 'JSON (in-app)'), ('csv', 'CSV / Excel'), ('pdf', 'PDF')], default='json', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('next_run', models.DateTimeField(blank=True, help_text='Datetime of next scheduled execution. Auto-updated after each run.', null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.reporttemplate')),
            ],
            options={
                'db_table': 'scheduled_reports',
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('bookings', 'Bookings'), ('revenue', 'Revenue'), ('occupancy', 'Occupancy'), ('guests', 'Guests'), ('staff', 'Staff Performance')], max_length=20)),
                ('config_snapshot', models.JSONField(default=dict, help_text='Copy of config at execution time (immutable record).')),
                ('export_format', models.CharField(choices=[('json', 'JSON (in-app)'), ('csv', 'CSV / Excel'), ('pdf', 'PDF')], max_length=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('result_data', models.JSONField(blank=True, help_text='Full report payload (summary + rows). Null on failure.', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_executions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, help_text='Null for ad-hoc runs not tied to a saved template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='reports.reporttemplate')),
                ('schedule', models.ForeignKey(blank=True, help_text='Null for on-demand runs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='reports.scheduledreport')),
            ],
            options={
                'db_table': 'report_executions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['created_by', 'report_type'], name='report_temp_created_4bf7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['is_shared'], name='report_temp_is_shar_fc5ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['report_type', '-started_at'], name='report_exec_report__600fee_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['triggered_by', '-started_at'], name='report_exec_trigger_cc7712_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['status'], name='report_exec_status_c1b883_idx'),
        ),
    ]
