# Generated by Django 6.0.2 on 2026-04-20 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportexecution',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Null for ad-hoc runs not tied to a saved template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='reports.reporttemplate'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.reporttemplate'),
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='Null for on-demand runs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='reports.scheduledreport'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['created_by', 'report_type'], name='report_temp_created_4bf7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['is_shared'], name='report_temp_is_shar_fc5ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['report_type', '-started_at'], name='report_exec_report__600fee_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['triggered_by', '-started_at'], name='report_exec_trigger_cc7712_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['status'], name='report_exec_status_c1b883_idx'),
        ),
    ]
