# Generated by Django 6.0.2 on 2026-04-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reportexecution_export_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportexecution',
            name='export_format',
            field=models.CharField(choices=[('json', 'JSON (in-app)'), ('csv', 'CSV'), ('pdf', 'PDF'), ('excel', 'Excel')], max_length=5),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='export_format',
            field=models.CharField(choices=[('json', 'JSON (in-app)'), ('csv', 'CSV'), ('pdf', 'PDF'), ('excel', 'Excel')], default='json', max_length=5),
        ),
    ]
