# Generated by Django 6.0.2 on 2026-04-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_reportexecution_export_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportexecution',
            name='report_type',
            field=models.CharField(choices=[('bookings', 'Bookings'), ('revenue', 'Revenue'), ('occupancy', 'Occupancy'), ('guests', 'Guests'), ('staff', 'Staff Performance'), ('food', 'Food & Drinks'), ('payments', 'Payments')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('bookings', 'Bookings'), ('revenue', 'Revenue'), ('occupancy', 'Occupancy'), ('guests', 'Guests'), ('staff', 'Staff Performance'), ('food', 'Food & Drinks'), ('payments', 'Payments')], db_index=True, max_length=20),
        ),
    ]
