# Generated by Django 6.0.2 on 2026-04-20 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('booking_created', 'New Booking Created'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_modified', 'Booking Modified'), ('deposit_received', 'Deposit Received'), ('full_payment_received', 'Full Payment Received'), ('payment_failed', 'Payment Failed'), ('balance_collected', 'Balance Collected'), ('guest_checked_in', 'Guest Checked In'), ('guest_checked_out', 'Guest Checked Out'), ('checkin_reminder', 'Check-in Reminder'), ('cleaning_task_assigned', 'Cleaning Task Assigned'), ('cleaning_task_overdue', 'Cleaning Task Overdue'), ('room_cleaned', 'Room Cleaned'), ('maintenance_assigned', 'Maintenance Task Assigned'), ('maintenance_overdue', 'Maintenance Task Overdue'), ('maintenance_completed', 'Maintenance Completed'), ('incident_reported', 'Incident Reported'), ('emergency_alert', 'Emergency Alert'), ('system_alert', 'System Alert')], max_length=40)),
                ('recipient_type', models.CharField(choices=[('guest', 'Guest'), ('admin', 'Admin'), ('manager', 'Manager'), ('front_desk', 'Front Desk'), ('housekeeping', 'Housekeeping'), ('maintenance', 'Maintenance'), ('security', 'Security'), ('staff', 'Staff (Generic)')], default='guest', max_length=15)),
                ('channel', models.CharField(choices=[('dashboard', 'Dashboard'), ('email', 'Email'), ('both', 'Both')], default='dashboard', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], db_index=True, default='unread', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bookings.booking')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
