# Generated by Django 6.0.2 on 2026-03-08 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_booking_confirmed_at_alter_booking_checkin_pin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('booking_created', 'New Booking Created'), ('deposit_received', 'Deposit Payment Received'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('checkin_reminder', 'Check-in Reminder')], help_text='The system event that triggered this notification', max_length=30)),
                ('recipient_type', models.CharField(choices=[('guest', 'Guest'), ('admin', 'Admin')], default='guest', max_length=10)),
                ('channel', models.CharField(choices=[('dashboard', 'Dashboard'), ('email', 'Email'), ('both', 'Both')], default='dashboard', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], db_index=True, default='unread', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Related booking (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bookings.booking')),
                ('recipient', models.ForeignKey(help_text='The user who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='notificatio_recipie_218e2a_idx'), models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_2d3764_idx'), models.Index(fields=['event'], name='notificatio_event_0dcf29_idx')],
            },
        ),
    ]
