# Generated by Django 6.0.2 on 2026-03-21 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_modifications'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('booking_created', 'New Booking Created'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('booking_modified', 'Booking Modified'), ('deposit_received', 'Deposit Received'), ('full_payment_received', 'Full Payment Received'), ('payment_failed', 'Payment Failed'), ('balance_collected', 'Balance Collected'), ('guest_checked_in', 'Guest Checked In'), ('guest_checked_out', 'Guest Checked Out'), ('checkin_reminder', 'Check-in Reminder'), ('cleaning_task_assigned', 'Cleaning Task Assigned'), ('cleaning_task_overdue', 'Cleaning Task Overdue'), ('room_cleaned', 'Room Cleaned'), ('maintenance_assigned', 'Maintenance Task Assigned'), ('maintenance_overdue', 'Maintenance Task Overdue'), ('maintenance_completed', 'Maintenance Completed'), ('incident_reported', 'Incident Reported'), ('emergency_alert', 'Emergency Alert'), ('system_alert', 'System Alert')], max_length=40),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_type',
            field=models.CharField(choices=[('guest', 'Guest'), ('admin', 'Admin'), ('manager', 'Manager'), ('front_desk', 'Front Desk'), ('housekeeping', 'Housekeeping'), ('maintenance', 'Maintenance'), ('security', 'Security'), ('staff', 'Staff (Generic)')], default='guest', max_length=15),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='notificatio_priorit_17ee5f_idx'),
        ),
    ]
