# Generated by Django 6.0.2 on 2026-04-20 01:52

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.TimeField(default='14:00')),
                ('checkout_time', models.TimeField(default='12:00')),
                ('hotel_name', models.CharField(default='Cebu Mini Hotel', max_length=255)),
                ('hotel_address', models.CharField(default='123 Colon St., Cebu City, 6000', max_length=500)),
                ('hotel_phone', models.CharField(default='+63 32 123 4567', max_length=50)),
                ('hotel_email', models.EmailField(blank=True, default='info@cebuminihotel.com', max_length=254)),
                ('hotel_description', models.TextField(blank=True, default='')),
                ('terms_url', models.CharField(default='/terms-and-conditions', max_length=500)),
                ('privacy_url', models.CharField(default='/privacy-policy', max_length=500)),
                ('cancellation_tiers', models.JSONField(blank=True, default=list, help_text='Ordered list of cancellation refund tiers.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotel Settings',
                'verbose_name_plural': 'Hotel Settings',
            },
        ),
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Icon identifier (e.g., 'coffee', 'pool', 'parking')", max_length=50)),
                ('category', models.CharField(blank=True, help_text='e.g., Food & Beverage, Facilities, Services', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_highlighted', models.BooleanField(default=False, help_text='Display with special prominence in UI')),
            ],
            options={
                'verbose_name': 'Inclusion',
                'verbose_name_plural': 'Inclusions',
                'db_table': 'room_inclusions_master',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpfulness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(help_text='True = thumbs up, False = thumbs down')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'review_helpfulness',
                'ordering': ['-voted_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Secure random UUID used in the review URL.', unique=True)),
                ('is_used', models.BooleanField(default=False, help_text='True after the guest submits their review.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Token is invalid after this datetime.')),
            ],
            options={
                'db_table': 'review_tokens',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('suite', 'Suite'), ('family', 'Family'), ('penthouse', 'Penthouse')], default='standard', max_length=20)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('bed_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('queen', 'Queen'), ('king', 'King'), ('twin', 'Twin')], default='double', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=2, help_text='Maximum number of guests allowed', validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved'), ('cleaning', 'Cleaning')], default='available', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('size_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Room size in square meters', max_digits=6, null=True)),
                ('panorama_image', models.ImageField(blank=True, help_text='360° panoramic image (equirectangular projection, 2:1 ratio)', null=True, upload_to='rooms/panoramas/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Display in homepage carousel')),
                ('view_type', models.CharField(choices=[('none', 'No Specific View'), ('city', 'City View'), ('sea', 'Sea View'), ('ocean', 'Ocean View'), ('pool', 'Pool View'), ('garden', 'Garden View'), ('mountain', 'Mountain View'), ('courtyard', 'Courtyard View')], default='none', max_length=20)),
                ('max_adults', models.PositiveIntegerField(default=2, help_text='Maximum number of adults', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_children', models.PositiveIntegerField(default=0, help_text='Maximum number of children')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount on base price', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cancellation_policy', models.TextField(blank=True, help_text='Cancellation terms and conditions')),
                ('checkin_time', models.TimeField(blank=True, help_text='Standard check-in time (e.g., 14:00)', null=True)),
                ('checkout_time', models.TimeField(blank=True, help_text='Standard check-out time (e.g., 11:00)', null=True)),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['floor', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='RoomAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Icon identifier (e.g., 'wifi', 'tv')", max_length=50)),
                ('category', models.CharField(blank=True, help_text='e.g., Technology, Comfort, Bathroom', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Room Amenities',
                'db_table': 'room_amenities',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoomAmenityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'room_amenity_assignments',
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/images/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'room_images',
                'ordering': ['-is_primary', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RoomInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, help_text='Optional specific details for this room', max_length=255)),
            ],
            options={
                'db_table': 'room_inclusion_assignments',
                'ordering': ['inclusion__category', 'inclusion__name'],
            },
        ),
        migrations.CreateModel(
            name='RoomPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'room_price_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, help_text='Full name of the reviewing guest. Populated from booking.full_name.', max_length=255)),
                ('guest_email', models.EmailField(blank=True, help_text='Email of the reviewing guest. Populated from booking.email.', max_length=254)),
                ('rating', models.PositiveIntegerField(help_text='Star rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, help_text='Optional written review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=True, help_text='Only verified bookings can leave reviews')),
                ('is_visible', models.BooleanField(default=True, help_text='Admin can hide inappropriate reviews')),
            ],
            options={
                'db_table': 'room_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomTemporaryLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=100)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('released', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'room_temporary_locks',
            },
        ),
        migrations.CreateModel(
            name='SeasonalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Christmas Week', 'Summer Peak', 'Weekend Rate'", max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('priority', models.IntegerField(choices=[(1, 'Low Priority'), (2, 'Normal Priority'), (3, 'High Priority'), (4, 'Peak Priority')], default=2, help_text='Higher priority overrides lower when dates overlap')),
                ('is_weekend_only', models.BooleanField(default=False, help_text='Apply only on Friday/Saturday nights')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'room_seasonal_prices',
                'ordering': ['-priority', 'start_date'],
            },
        ),
    ]
