# Generated by Django 6.0.2 on 2026-02-17 13:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Icon identifier (e.g., 'wifi', 'tv')", max_length=50)),
                ('category', models.CharField(blank=True, help_text='e.g., Technology, Comfort, Bathroom', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Room Amenities',
                'db_table': 'room_amenities',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('suite', 'Suite'), ('family', 'Family'), ('penthouse', 'Penthouse')], default='standard', max_length=20)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('bed_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('queen', 'Queen'), ('king', 'King'), ('twin', 'Twin')], default='double', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=2, help_text='Maximum number of guests allowed', validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('size_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Room size in square meters', max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['floor', 'room_number'],
                'indexes': [models.Index(fields=['room_type', 'status'], name='rooms_room_ty_359c15_idx'), models.Index(fields=['price_per_night'], name='rooms_price_p_db2697_idx'), models.Index(fields=['capacity'], name='rooms_capacit_c8100e_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/images/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room')),
            ],
            options={
                'db_table': 'room_images',
                'ordering': ['-is_primary', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RoomPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_price_changes', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='rooms.room')),
            ],
            options={
                'db_table': 'room_price_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomAmenityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to='rooms.roomamenity')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_assignments', to='rooms.room')),
            ],
            options={
                'db_table': 'room_amenity_assignments',
                'unique_together': {('room', 'amenity')},
            },
        ),
        migrations.CreateModel(
            name='RoomTemporaryLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=100)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('released', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='rooms.room')),
            ],
            options={
                'db_table': 'room_temporary_locks',
                'indexes': [models.Index(fields=['room', 'check_in', 'check_out'], name='room_tempor_room_id_155664_idx'), models.Index(fields=['expires_at', 'released'], name='room_tempor_expires_67c687_idx')],
            },
        ),
    ]
