# Generated by Django 6.0.2 on 2026-04-20 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewhelpfulness',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewtoken',
            name='booking',
            field=models.OneToOneField(help_text='One review token per booking.', on_delete=django.db.models.deletion.CASCADE, related_name='review_token', to='bookings.booking'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type', 'status'], name='rooms_room_ty_359c15_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['price_per_night'], name='rooms_price_p_db2697_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['capacity'], name='rooms_capacit_c8100e_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_featured'], name='rooms_is_feat_cfed9a_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['view_type'], name='rooms_view_ty_06aa7a_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['-discount_percentage'], name='rooms_discoun_eef2c9_idx'),
        ),
        migrations.AddField(
            model_name='roomamenityassignment',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to='rooms.roomamenity'),
        ),
        migrations.AddField(
            model_name='roomamenityassignment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_assignments', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='roominclusion',
            name='inclusion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to='rooms.inclusion'),
        ),
        migrations.AddField(
            model_name='roominclusion',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_inclusions', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='roompricehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_price_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roompricehistory',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='roomreview',
            name='booking',
            field=models.OneToOneField(help_text='One review per booking', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='roomreview',
            name='guest',
            field=models.ForeignKey(blank=True, help_text='Null for walk-in guests who have no account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roomreview',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='reviewhelpfulness',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpfulness_votes', to='rooms.roomreview'),
        ),
        migrations.AddField(
            model_name='roomtemporarylock',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='seasonalprice',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_prices', to='rooms.room'),
        ),
        migrations.AddIndex(
            model_name='reviewtoken',
            index=models.Index(fields=['token'], name='review_toke_token_583094_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewtoken',
            index=models.Index(fields=['is_used', 'expires_at'], name='review_toke_is_used_90644f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomamenityassignment',
            unique_together={('room', 'amenity')},
        ),
        migrations.AlterUniqueTogether(
            name='roominclusion',
            unique_together={('room', 'inclusion')},
        ),
        migrations.AddIndex(
            model_name='roomreview',
            index=models.Index(fields=['room', '-created_at'], name='room_review_room_id_0a75bf_idx'),
        ),
        migrations.AddIndex(
            model_name='roomreview',
            index=models.Index(fields=['rating'], name='room_review_rating_98890d_idx'),
        ),
        migrations.AddConstraint(
            model_name='roomreview',
            constraint=models.UniqueConstraint(fields=('booking',), name='unique_review_per_booking'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewhelpfulness',
            unique_together={('review', 'user')},
        ),
        migrations.AddIndex(
            model_name='roomtemporarylock',
            index=models.Index(fields=['room', 'check_in', 'check_out'], name='room_tempor_room_id_155664_idx'),
        ),
        migrations.AddIndex(
            model_name='roomtemporarylock',
            index=models.Index(fields=['expires_at', 'released'], name='room_tempor_expires_67c687_idx'),
        ),
        migrations.AddIndex(
            model_name='seasonalprice',
            index=models.Index(fields=['room', 'start_date', 'end_date'], name='room_season_room_id_c8a1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='seasonalprice',
            index=models.Index(fields=['priority', 'is_active'], name='room_season_priorit_2152d7_idx'),
        ),
    ]
