# Generated by Django 6.0.2 on 2026-04-24 15:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='panorama_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='360° panoramic image (equirectangular projection, 2:1 ratio)', max_length=255, null=True, verbose_name='panorama'),
        ),
        migrations.AlterField(
            model_name='roomimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
