# Generated by Django 6.0.2 on 2026-02-28 12:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('rooms', '0002_room_panorama_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Star rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, help_text='Optional written review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=True, help_text='Only verified bookings can leave reviews')),
                ('is_visible', models.BooleanField(default=True, help_text='Admin can hide inappropriate reviews')),
                ('booking', models.OneToOneField(help_text='One review per booking', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reviews', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rooms.room')),
            ],
            options={
                'db_table': 'room_reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['room', '-created_at'], name='room_review_room_id_0a75bf_idx'), models.Index(fields=['rating'], name='room_review_rating_98890d_idx')],
                'constraints': [models.UniqueConstraint(fields=('booking',), name='unique_review_per_booking')],
            },
        ),
    ]
