# Generated by Django 6.0.2 on 2026-03-03 08:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_reviewhelpfulness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Icon identifier (e.g., 'coffee', 'pool', 'parking')", max_length=50)),
                ('category', models.CharField(blank=True, help_text='e.g., Food & Beverage, Facilities, Services', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_highlighted', models.BooleanField(default=False, help_text='Display with special prominence in UI')),
            ],
            options={
                'verbose_name': 'Inclusion',
                'verbose_name_plural': 'Inclusions',
                'db_table': 'room_inclusions_master',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoomInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, help_text='Optional specific details for this room', max_length=255)),
            ],
            options={
                'db_table': 'room_inclusion_assignments',
                'ordering': ['inclusion__category', 'inclusion__name'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Christmas Week', 'Summer Peak', 'Weekend Rate'", max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('priority', models.IntegerField(choices=[(1, 'Low Priority'), (2, 'Normal Priority'), (3, 'High Priority'), (4, 'Peak Priority')], default=2, help_text='Higher priority overrides lower when dates overlap')),
                ('is_weekend_only', models.BooleanField(default=False, help_text='Apply only on Friday/Saturday nights')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'room_seasonal_prices',
                'ordering': ['-priority', 'start_date'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='cancellation_policy',
            field=models.TextField(blank=True, help_text='Cancellation terms and conditions'),
        ),
        migrations.AddField(
            model_name='room',
            name='checkin_time',
            field=models.TimeField(blank=True, help_text='Standard check-in time (e.g., 14:00)', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='checkout_time',
            field=models.TimeField(blank=True, help_text='Standard check-out time (e.g., 11:00)', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount on base price', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='room',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Display in homepage carousel'),
        ),
        migrations.AddField(
            model_name='room',
            name='max_adults',
            field=models.PositiveIntegerField(default=2, help_text='Maximum number of adults', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='room',
            name='max_children',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of children'),
        ),
        migrations.AddField(
            model_name='room',
            name='view_type',
            field=models.CharField(choices=[('none', 'No Specific View'), ('city', 'City View'), ('sea', 'Sea View'), ('ocean', 'Ocean View'), ('pool', 'Pool View'), ('garden', 'Garden View'), ('mountain', 'Mountain View'), ('courtyard', 'Courtyard View')], default='none', max_length=20),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_featured'], name='rooms_is_feat_cfed9a_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['view_type'], name='rooms_view_ty_06aa7a_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['-discount_percentage'], name='rooms_discoun_eef2c9_idx'),
        ),
        migrations.AddField(
            model_name='roominclusion',
            name='inclusion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to='rooms.inclusion'),
        ),
        migrations.AddField(
            model_name='roominclusion',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_inclusions', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='seasonalprice',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_prices', to='rooms.room'),
        ),
        migrations.AlterUniqueTogether(
            name='roominclusion',
            unique_together={('room', 'inclusion')},
        ),
        migrations.AddIndex(
            model_name='seasonalprice',
            index=models.Index(fields=['room', 'start_date', 'end_date'], name='room_season_room_id_c8a1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='seasonalprice',
            index=models.Index(fields=['priority', 'is_active'], name='room_season_priorit_2152d7_idx'),
        ),
    ]
