# Generated by Django 6.0.2 on 2026-04-03 13:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_modifications'),
        ('rooms', '0006_alter_room_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreview',
            name='guest_email',
            field=models.EmailField(blank=True, help_text='Email of the reviewing guest. Populated from booking.email.', max_length=254),
        ),
        migrations.AddField(
            model_name='roomreview',
            name='guest_name',
            field=models.CharField(blank=True, help_text='Full name of the reviewing guest. Populated from booking.full_name.', max_length=255),
        ),
        migrations.AlterField(
            model_name='roomreview',
            name='guest',
            field=models.ForeignKey(blank=True, help_text='Null for walk-in guests who have no account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReviewToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Secure random UUID used in the review URL.', unique=True)),
                ('is_used', models.BooleanField(default=False, help_text='True after the guest submits their review.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Token is invalid after this datetime.')),
                ('booking', models.OneToOneField(help_text='One review token per booking.', on_delete=django.db.models.deletion.CASCADE, related_name='review_token', to='bookings.booking')),
            ],
            options={
                'db_table': 'review_tokens',
                'indexes': [models.Index(fields=['token'], name='review_toke_token_583094_idx'), models.Index(fields=['is_used', 'expires_at'], name='review_toke_is_used_90644f_idx')],
            },
        ),
    ]
