# Generated by Django 6.0.2 on 2026-04-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_roomreview_guest_email_roomreview_guest_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.TimeField(default='14:00')),
                ('checkout_time', models.TimeField(default='12:00')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotel Settings',
                'verbose_name_plural': 'Hotel Settings',
            },
        ),
    ]
