# Generated by Django 6.0.2 on 2026-04-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_hotelsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsettings',
            name='cancellation_tiers',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of cancellation refund tiers.'),
        ),
    ]
