# Generated by Django 6.0.2 on 2026-04-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_hotelsettings_cancellation_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsettings',
            name='hotel_address',
            field=models.CharField(default='123 Colon St., Cebu City, 6000', max_length=500),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='hotel_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='hotel_email',
            field=models.EmailField(blank=True, default='info@cebuminihotel.com', max_length=254),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='hotel_name',
            field=models.CharField(default='Cebu Mini Hotel', max_length=255),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='hotel_phone',
            field=models.CharField(default='+63 32 123 4567', max_length=50),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='privacy_url',
            field=models.CharField(default='/privacy-policy', max_length=500),
        ),
        migrations.AddField(
            model_name='hotelsettings',
            name='terms_url',
            field=models.CharField(default='/terms-and-conditions', max_length=500),
        ),
    ]
