# Generated by Django 6.0.2 on 2026-04-20 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('food', 'Food'), ('drinks', 'Drinks'), ('snacks', 'Snacks'), ('desserts', 'Desserts')], db_index=True, default='food', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food/')),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'food_items',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Snapshot of price at time of order.', max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('pay_now', 'Pay Now'), ('pay_checkout', 'Pay at Checkout')], max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], db_index=True, default='unpaid', max_length=10)),
                ('order_status', models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('pending', 'Pending'), ('preparing', 'Preparing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('paymongo_session_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Guest notes for this order.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(help_text='The active booking this order is attached to.', on_delete=django.db.models.deletion.CASCADE, related_name='food_orders', to='bookings.booking')),
            ],
            options={
                'db_table': 'food_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
