# Generated by Django 6.0.2 on 2026-04-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodorder',
            old_name='paymongo_payment_id',
            new_name='paymongo_session_id',
        ),
    ]
