# Generated by Django 6.0.2 on 2026-04-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_paymongo_payment_id_foodorder_paymongo_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='order_status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
