# Generated by Django 6.0.2 on 2026-04-20 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='foodorder',
            index=models.Index(fields=['order_status'], name='food_orders_order_s_e8cfdd_idx'),
        ),
        migrations.AddIndex(
            model_name='foodorder',
            index=models.Index(fields=['booking', 'order_status'], name='food_orders_booking_119437_idx'),
        ),
        migrations.AddIndex(
            model_name='foodorder',
            index=models.Index(fields=['guest', 'created_at'], name='food_orders_guest_i_e19c10_idx'),
        ),
    ]
