# Generated by Django 6.0.2 on 2026-04-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Used to track anonymous users across requests.', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('support', 'Escalated to Support'), ('closed', 'Closed')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chatbot_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('bot', 'Bot'), ('support', 'Support Agent')], db_index=True, default='user', max_length=10)),
                ('message_text', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional structured data (e.g. room list, booking info).')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'chatbot_messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('escalated', 'Escalated'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('tier', models.CharField(choices=[('front_desk', 'Front Desk'), ('manager', 'Manager'), ('admin', 'Admin')], db_index=True, default='front_desk', help_text='Which staff tier currently owns this ticket.', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='normal', max_length=10)),
                ('category', models.CharField(choices=[('booking_inquiry', 'Booking Inquiry'), ('payment_issue', 'Payment Issue'), ('room_complaint', 'Room Complaint'), ('cancellation', 'Cancellation / Refund'), ('vip_request', 'VIP Request'), ('technical_error', 'Technical Error'), ('general_inquiry', 'General Inquiry'), ('security_concern', 'Security Concern'), ('other', 'Other')], db_index=True, default='general_inquiry', help_text='Issue category used for routing and analytics.', max_length=30)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Internal notes from support staff.')),
                ('escalated_at', models.DateTimeField(blank=True, help_text='When this ticket was last escalated to a higher tier.', null=True)),
                ('escalation_reason', models.TextField(blank=True, help_text='Reason recorded when escalating to Manager/Admin.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chatbot_support_tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
