# Generated by Django 6.0.2 on 2026-04-20 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(blank=True, help_text='NULL for unauthenticated users.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='sent_by_staff',
            field=models.ForeignKey(blank=True, help_text='Only set when sender=support.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='conversation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_ticket', to='chatbot.conversation'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='escalated_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who triggered the last escalation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'status'], name='chatbot_con_user_id_8e3d38_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['session_key'], name='chatbot_con_session_df9902_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'timestamp'], name='chatbot_mes_convers_90de13_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status'], name='chatbot_sup_status_e2383a_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['tier', 'status'], name='chatbot_sup_tier_d0f1ce_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['priority', 'tier'], name='chatbot_sup_priorit_aceb78_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['assigned_to', 'status'], name='chatbot_sup_assigne_f6721e_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['category'], name='chatbot_sup_categor_0df789_idx'),
        ),
    ]
