# Generated by Django 6.0.2 on 2026-04-03 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='category',
            field=models.CharField(choices=[('booking_inquiry', 'Booking Inquiry'), ('payment_issue', 'Payment Issue'), ('room_complaint', 'Room Complaint'), ('cancellation', 'Cancellation / Refund'), ('vip_request', 'VIP Request'), ('technical_error', 'Technical Error'), ('general_inquiry', 'General Inquiry'), ('security_concern', 'Security Concern'), ('other', 'Other')], db_index=True, default='general_inquiry', help_text='Issue category used for routing and analytics.', max_length=30),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='escalated_at',
            field=models.DateTimeField(blank=True, help_text='When this ticket was last escalated to a higher tier.', null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='escalated_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who triggered the last escalation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='escalation_reason',
            field=models.TextField(blank=True, help_text='Reason recorded when escalating to Manager/Admin.'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='tier',
            field=models.CharField(choices=[('front_desk', 'Front Desk'), ('manager', 'Manager'), ('admin', 'Admin')], db_index=True, default='front_desk', help_text='Which staff tier currently owns this ticket.', max_length=20),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('escalated', 'Escalated'), ('closed', 'Closed')], db_index=True, default='open', max_length=20),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['tier', 'status'], name='chatbot_sup_tier_d0f1ce_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['priority', 'tier'], name='chatbot_sup_priorit_aceb78_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['category'], name='chatbot_sup_categor_0df789_idx'),
        ),
    ]
