# Generated by Django 6.0.2 on 2026-02-22 13:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, help_text='Auto-generated on payment success.', max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='PHP', max_length=3)),
                ('payment_type', models.CharField(choices=[('full_payment', 'Full Payment'), ('deposit', 'Deposit (30%)'), ('balance_payment', 'Balance Payment')], default='full_payment', max_length=20)),
                ('provider', models.CharField(choices=[('paymongo', 'PayMongo'), ('paypal', 'PayPal'), ('manual', 'Manual (Cash / Walk-in)')], default='paymongo', max_length=20)),
                ('payment_method', models.CharField(choices=[('card', 'Credit / Debit Card'), ('gcash', 'GCash'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('cash', 'Cash (Walk-in)')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Provider transaction / payment intent ID.', max_length=255, null=True)),
                ('checkout_url', models.URLField(blank=True, help_text='Redirect URL returned by provider.', null=True)),
                ('checkout_session_id', models.CharField(blank=True, help_text='PayMongo link_id or PayPal order_id.', max_length=255, null=True)),
                ('provider_payload', models.JSONField(blank=True, help_text='Raw webhook payload for audit / debugging.', null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the pending checkout session expires.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking')),
                ('user', models.ForeignKey(blank=True, help_text='Null for anonymous / walk-in guests.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('provider_refund_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_refunds', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment')),
            ],
            options={
                'db_table': 'payment_refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking', 'status'], name='payments_booking_52233d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_status_d621e5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='payments_transac_a1f824_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['checkout_session_id'], name='payments_checkou_ea497d_idx'),
        ),
    ]
