# Generated by Django 6.0.2 on 2026-02-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, default=None, help_text='Auto-generated on payment success. NULL while pending.', max_length=20, null=True, unique=True),
        ),
    ]
