# Generated by Django 6.0.2 on 2026-03-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_amount_alter_payment_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('full_payment', 'Full Payment'), ('deposit', 'Deposit (30%)'), ('balance_payment', 'Balance Payment'), ('modification', 'Booking Modification')], default='full_payment', max_length=20),
        ),
    ]
