from django.contrib import admin
from .models import Booking, BookingStatusHistory


class BookingStatusHistoryInline(admin.TabularInline):
    model           = BookingStatusHistory
    extra           = 0
    readonly_fields = ["old_status", "new_status", "changed_by", "note", "changed_at"]
    can_delete      = False


@admin.register(Booking)
class BookingAdmin(admin.ModelAdmin):
    list_display = [
        "id", "reference_number", "full_name", "room",
        "check_in", "check_out", "nights",
        "total_price", "status", "payment_status",
        "has_credentials", "created_at",
    ]
    list_filter   = ["status", "payment_status", "check_in"]
    search_fields = ["reference_number", "full_name", "email", "phone"]

    # reference_number and checkin_pin are editable=False on the model,
    # but we also mark confirmed_at, nights, price fields readonly here.
    readonly_fields = [
        # Credentials — generated by confirm_after_payment() only
        "reference_number", "checkin_pin",
        # Computed / auto fields
        "nights", "room_price_snapshot", "subtotal", "tax", "service_fee", "total_price",
        "confirmed_at", "created_at", "updated_at",
        # Virtual property
        "has_credentials", "is_expired", "payment_deadline",
    ]
    inlines = [BookingStatusHistoryInline]

    fieldsets = (
        ("Credentials (generated after payment)", {
            "fields": ("reference_number", "checkin_pin"),
            "description": (
                "These fields are NULL until payment is confirmed. "
                "Use the /admin/<id>/confirm/ endpoint to generate them."
            ),
        }),
        ("Relations",   {"fields": ("user", "room")}),
        ("Guest",       {"fields": ("full_name", "email", "phone")}),
        ("Stay",        {"fields": ("check_in", "check_out", "nights", "guests_count")}),
        ("Pricing",     {"fields": ("room_price_snapshot", "subtotal", "tax", "service_fee", "total_price")}),
        ("Status",      {"fields": ("status", "payment_status")}),
        ("Confirmation", {"fields": ("confirmed_at",)}),
        ("Cancellation", {"fields": (
            "cancelled_at", "cancellation_reason",
            "refund_percentage", "refund_amount", "refund_status",
        )}),
        ("Flags",       {"fields": ("has_credentials", "is_expired", "payment_deadline")}),
        ("Timestamps",  {"fields": ("created_at", "updated_at")}),
    )

    def has_credentials(self, obj):
        return obj.has_credentials
    has_credentials.boolean = True
    has_credentials.short_description = "Credentials?"


@admin.register(BookingStatusHistory)
class BookingStatusHistoryAdmin(admin.ModelAdmin):
    list_display  = ["booking", "old_status", "new_status", "changed_by", "changed_at"]
    list_filter   = ["new_status"]
    search_fields = ["booking__reference_number"]
    readonly_fields = ["booking", "old_status", "new_status", "changed_by", "changed_at"]