# Generated by Django 6.0.2 on 2026-03-09 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_booking_confirmed_at_alter_booking_checkin_pin_and_more'),
        ('rooms', '0005_inclusion_roominclusion_seasonalprice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin (Super Admin)'), ('manager', 'Manager'), ('receptionist', 'Receptionist'), ('front_desk', 'Front Desk'), ('housekeeping', 'Housekeeping'), ('maintenance', 'Maintenance'), ('security', 'Security')], db_index=True, default='receptionist', max_length=20)),
                ('temp_role', models.CharField(blank=True, choices=[('admin', 'Admin (Super Admin)'), ('manager', 'Manager'), ('receptionist', 'Receptionist'), ('front_desk', 'Front Desk'), ('housekeeping', 'Housekeeping'), ('maintenance', 'Maintenance'), ('security', 'Security')], max_length=20, null=True)),
                ('temp_role_expires_at', models.DateTimeField(blank=True, help_text='When set, temp_role is active until this datetime.', null=True)),
                ('online_status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('idle', 'Idle')], db_index=True, default='offline', max_length=10)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('current_task', models.CharField(blank=True, help_text='Short description of what this staff member is currently doing.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivated staff cannot log in.')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_staff', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='The Django user this profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff_profiles',
                'ordering': ['user__email'],
            },
        ),
        migrations.CreateModel(
            name='StaffActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(db_index=True, max_length=60)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('booking_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('room_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('target_user_id', models.IntegerField(blank=True, help_text='If the action involves another user (e.g. promoting staff).', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='staff.staffprofile')),
            ],
            options={
                'db_table': 'staff_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="e.g. 'Morning Shift'", max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_shift', 'In Shift'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shifts', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='staff.staffprofile')),
            ],
            options={
                'db_table': 'staff_shifts',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=15)),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Normal'), (3, 'Low')], db_index=True, default=2)),
                ('completion_notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Booking linked to this request (if guest-reported).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tasks', to='bookings.booking')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_tasks', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tasks', to='rooms.room')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'maintenance'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tasks', to='staff.staffprofile')),
            ],
            options={
                'db_table': 'maintenance_tasks',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('lost_item', 'Lost Item'), ('disturbance', 'Disturbance'), ('trespassing', 'Trespassing'), ('medical', 'Medical Emergency'), ('theft', 'Theft'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('location', models.CharField(blank=True, help_text="e.g. 'Room 205', 'Lobby', 'Parking'", max_length=200)),
                ('description', models.TextField()),
                ('involved_guests', models.TextField(blank=True, help_text='Names / booking references of involved guests.')),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_logs', to='staff.staffprofile')),
            ],
            options={
                'db_table': 'incident_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CleaningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('dirty', 'Dirty'), ('cleaning', 'Cleaning'), ('clean', 'Clean / Ready')], db_index=True, default='dirty', max_length=15)),
                ('priority', models.PositiveSmallIntegerField(default=2, help_text='1=High, 2=Normal, 3=Low')),
                ('notes', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, help_text='The checkout booking that triggered this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_tasks', to='bookings.booking')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cleaning_tasks', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_tasks', to='rooms.room')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'housekeeping'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_tasks', to='staff.staffprofile')),
            ],
            options={
                'db_table': 'cleaning_tasks',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('logged_in_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('logged_out_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='staff.staffprofile')),
            ],
            options={
                'db_table': 'staff_sessions',
                'ordering': ['-logged_in_at'],
            },
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['role'], name='staff_profi_role_388618_idx'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['online_status'], name='staff_profi_online__c3114a_idx'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['is_active'], name='staff_profi_is_acti_7aefb7_idx'),
        ),
        migrations.AddIndex(
            model_name='staffactivitylog',
            index=models.Index(fields=['action_type', 'created_at'], name='staff_activ_action__e6fbff_idx'),
        ),
        migrations.AddIndex(
            model_name='staffactivitylog',
            index=models.Index(fields=['staff', 'created_at'], name='staff_activ_staff_i_d816d6_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancetask',
            index=models.Index(fields=['status'], name='maintenance_status_761b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancetask',
            index=models.Index(fields=['room', 'status'], name='maintenance_room_id_b37b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningtask',
            index=models.Index(fields=['status'], name='cleaning_ta_status_91ecb0_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningtask',
            index=models.Index(fields=['room', 'status'], name='cleaning_ta_room_id_e895b5_idx'),
        ),
    ]
