# Generated by Django 6.0.2 on 2026-04-20 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="Short descriptive title, e.g. 'Broken door lock Room 205'.", max_length=200)),
                ('incident_type', models.CharField(choices=[('lost_item', 'Lost Item'), ('disturbance', 'Disturbance'), ('trespassing', 'Trespassing'), ('medical', 'Medical Emergency'), ('theft', 'Theft'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('under_investigation', 'Under Investigation'), ('resolved', 'Resolved')], db_index=True, default='reported', max_length=25)),
                ('location', models.CharField(blank=True, help_text="e.g. 'Room 205', 'Lobby', 'Parking'", max_length=200)),
                ('description', models.TextField()),
                ('involved_guests', models.TextField(blank=True, help_text='Names / booking references of involved guests.')),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'incident_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('converted_to_task', 'Converted to Task')], db_index=True, default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, help_text='Notes added by Admin/Manager during review.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'maintenance_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=15)),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], db_index=True, default=2)),
                ('deadline', models.DateTimeField(blank=True, db_index=True, help_text='Expected completion deadline. Used for overdue alerts.', null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('staff_notes', models.TextField(blank=True, help_text='Progress notes added by maintenance staff.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'maintenance_tasks',
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="e.g. 'Morning Shift'", max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_shift', 'In Shift'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'staff_shifts',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='StaffActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(db_index=True, max_length=60)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('booking_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('room_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('target_user_id', models.IntegerField(blank=True, help_text='If the action involves another user (e.g. promoting staff).', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'staff_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin (Super Admin)'), ('manager', 'Manager'), ('receptionist', 'Receptionist'), ('front_desk', 'Front Desk'), ('housekeeping', 'Housekeeping'), ('maintenance', 'Maintenance'), ('security', 'Security'), ('kitchen_staff', 'Kitchen Staff')], db_index=True, default='receptionist', max_length=20)),
                ('temp_role', models.CharField(blank=True, choices=[('admin', 'Admin (Super Admin)'), ('manager', 'Manager'), ('receptionist', 'Receptionist'), ('front_desk', 'Front Desk'), ('housekeeping', 'Housekeeping'), ('maintenance', 'Maintenance'), ('security', 'Security'), ('kitchen_staff', 'Kitchen Staff')], max_length=20, null=True)),
                ('temp_role_expires_at', models.DateTimeField(blank=True, help_text='When set, temp_role is active until this datetime.', null=True)),
                ('online_status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('idle', 'Idle')], db_index=True, default='offline', max_length=10)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('current_task', models.CharField(blank=True, help_text='Short description of what this staff member is currently doing.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivated staff cannot log in.')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'staff_profiles',
                'ordering': ['user__email'],
            },
        ),
        migrations.CreateModel(
            name='StaffSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('logged_in_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('logged_out_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'staff_sessions',
                'ordering': ['-logged_in_at'],
            },
        ),
        migrations.CreateModel(
            name='CleaningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('dirty', 'Dirty'), ('cleaning', 'Cleaning'), ('clean', 'Clean / Ready')], db_index=True, default='dirty', max_length=15)),
                ('priority', models.PositiveSmallIntegerField(default=2, help_text='1=High, 2=Normal, 3=Low')),
                ('notes', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cleaning_started_at', models.DateTimeField(blank=True, help_text='Set automatically when room enters CLEANING status on checkout.', null=True)),
                ('cleaning_end_at', models.DateTimeField(blank=True, help_text='Set automatically to cleaning_started_at + 2 hours.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, help_text='The checkout booking that triggered this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_tasks', to='bookings.booking')),
            ],
            options={
                'db_table': 'cleaning_tasks',
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
