# Generated by Django 6.0.2 on 2026-03-20 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_modifications'),
        ('rooms', '0006_alter_room_status'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningtask',
            name='cleaning_end_at',
            field=models.DateTimeField(blank=True, help_text='Set automatically to cleaning_started_at + 2 hours.', null=True),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='cleaning_started_at',
            field=models.DateTimeField(blank=True, help_text='Set automatically when room enters CLEANING status on checkout.', null=True),
        ),
        migrations.AddIndex(
            model_name='cleaningtask',
            index=models.Index(fields=['cleaning_end_at'], name='cleaning_ta_cleanin_d926b0_idx'),
        ),
    ]
