# Generated by Django 6.0.2 on 2026-04-20 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_initial'),
        ('rooms', '0002_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningtask',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cleaning_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_tasks', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='reported_by',
            field=models.ForeignKey(help_text='Front Desk or Housekeeping staff who submitted this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Room this issue was observed in (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Booking linked to this request (if guest-reported).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tasks', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='reported_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who originally reported/created this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_maintenance_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tasks', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='converted_task',
            field=models.OneToOneField(blank=True, help_text='The MaintenanceTask created from this request (if converted).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='staff.maintenancetask'),
        ),
        migrations.AddField(
            model_name='shift',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='user',
            field=models.OneToOneField(help_text='The Django user this profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffactivitylog',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='shift',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'maintenance'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tasks', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='incidentlog',
            name='logged_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_logs', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'housekeeping'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_tasks', to='staff.staffprofile'),
        ),
        migrations.AddField(
            model_name='staffsession',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='staff.staffprofile'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['status'], name='maintenance_status_b8d89d_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['reported_by', 'created_at'], name='maintenance_reporte_4ac1f3_idx'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['role'], name='staff_profi_role_388618_idx'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['online_status'], name='staff_profi_online__c3114a_idx'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['is_active'], name='staff_profi_is_acti_7aefb7_idx'),
        ),
        migrations.AddIndex(
            model_name='staffactivitylog',
            index=models.Index(fields=['action_type', 'created_at'], name='staff_activ_action__e6fbff_idx'),
        ),
        migrations.AddIndex(
            model_name='staffactivitylog',
            index=models.Index(fields=['staff', 'created_at'], name='staff_activ_staff_i_d816d6_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancetask',
            index=models.Index(fields=['status'], name='maintenance_status_761b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancetask',
            index=models.Index(fields=['room', 'status'], name='maintenance_room_id_b37b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancetask',
            index=models.Index(fields=['deadline'], name='maintenance_deadlin_ad08e1_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentlog',
            index=models.Index(fields=['status'], name='incident_lo_status_051b65_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentlog',
            index=models.Index(fields=['severity'], name='incident_lo_severit_010530_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningtask',
            index=models.Index(fields=['status'], name='cleaning_ta_status_91ecb0_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningtask',
            index=models.Index(fields=['room', 'status'], name='cleaning_ta_room_id_e895b5_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningtask',
            index=models.Index(fields=['cleaning_end_at'], name='cleaning_ta_cleanin_d926b0_idx'),
        ),
    ]
