# Generated by Django 6.0.2 on 2026-03-22 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_modifications'),
        ('rooms', '0006_alter_room_status'),
        ('staff', '0002_add_cleaning_window_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('converted_to_task', 'Converted to Task')], db_index=True, default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, help_text='Notes added by Admin/Manager during review.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'maintenance_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='incidentlog',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('under_investigation', 'Under Investigation'), ('resolved', 'Resolved')], db_index=True, default='reported', max_length=25),
        ),
        migrations.AddField(
            model_name='incidentlog',
            name='title',
            field=models.CharField(blank=True, help_text="Short descriptive title, e.g. 'Broken door lock Room 205'.", max_length=200),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='deadline',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Expected completion deadline. Used for overdue alerts.', null=True),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='reported_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who originally reported/created this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_maintenance_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incidentlog',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], db_index=True, default=2),
        ),
        migrations.AddIndex(
            model_name='incidentlog',
            index=models.Index(fields=['status'], name='incident_lo_status_051b65_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentlog',
            index=models.Index(fields=['severity'], name='incident_lo_severit_010530_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancetask',
            index=models.Index(fields=['deadline'], name='maintenance_deadlin_ad08e1_idx'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='converted_task',
            field=models.OneToOneField(blank=True, help_text='The MaintenanceTask created from this request (if converted).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='staff.maintenancetask'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='reported_by',
            field=models.ForeignKey(help_text='Front Desk or Housekeeping staff who submitted this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Room this issue was observed in (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='rooms.room'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['status'], name='maintenance_status_b8d89d_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['reported_by', 'created_at'], name='maintenance_reporte_4ac1f3_idx'),
        ),
    ]
