# Generated by Django 6.0.2 on 2026-04-24 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_panorama_image_alter_roomimage_image'),
        ('staff', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetask',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tasks', to='rooms.room'),
        ),
    ]
