# Generated by Django 6.0.2 on 2026-04-25 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_maintenancetask_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentlog',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Security staff member assigned to investigate this incident.', limit_choices_to={'role': 'security'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to='staff.staffprofile'),
        ),
    ]
