# Generated by Django 6.0.2 on 2026-03-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_maintenancerequest_incidentlog_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='staff_notes',
            field=models.TextField(blank=True, help_text='Progress notes added by maintenance staff.'),
        ),
    ]
