# Generated by Django 6.0.2 on 2026-04-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_maintenancetask_staff_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin (Super Admin)'), ('manager', 'Manager'), ('receptionist', 'Receptionist'), ('front_desk', 'Front Desk'), ('housekeeping', 'Housekeeping'), ('maintenance', 'Maintenance'), ('security', 'Security'), ('kitchen_staff', 'Kitchen Staff')], db_index=True, default='receptionist', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='temp_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin (Super Admin)'), ('manager', 'Manager'), ('receptionist', 'Receptionist'), ('front_desk', 'Front Desk'), ('housekeeping', 'Housekeeping'), ('maintenance', 'Maintenance'), ('security', 'Security'), ('kitchen_staff', 'Kitchen Staff')], max_length=20, null=True),
        ),
    ]
